name: Build a Release

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Release name (e.g. "lxd-4.0.3")'
        default: 'lxd-4.0.3'
        required: true

jobs:
  build:
    name: Build ${{ github.event.inputs.release_name }} for ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Fetch release
      env:
        TARBALL_URL: https://linuxcontainers.org/downloads/lxd/${{ github.event.inputs.release_name }}.tar.gz
      run: |
        curl --fail --show-error --silent --location --output lxd.tar.gz $TARBALL_URL
        curl --fail --show-error --silent --location --output lxd.tar.gz.asc $TARBALL_URL.asc
        
    - name: Fetch key signatures
      # signing key IDs via https://discuss.linuxcontainers.org/t/why-is-there-no-go-sum-file-or-vendors-directory-in-the-distrobuilder-source/8625/4
      if: ${{ maatrix.os != 'ubuntu-18.04' }}
      run: gpg --recv-keys 0xC638974D64792D67 0x7B3C391EFEA93624
        
    - name: Fetch key signatures (bionic)
      if: ${{ matrix.os == 'ubuntu-18.04' }}
      run: |
        gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0xC638974D64792D67 0x7B3C391EFEA93624
        
    - name: Verify release signature
      run: |
        gpg --verify lxd.tar.gz.asc lxd.tar.gz
        tar -xzf lxd.tar.gz
        mv ${{ github.event.inputs.release_name }} lxd

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y acl autoconf dnsmasq-base libacl1-dev libcap-dev liblxc1 liblxc-dev libsqlite3-dev libtool libudev-dev libuv1-dev make pkg-config rsync squashfs-tools tar tcl xz-utils ebtables

    - name: Make deps
      run: |
        export GOPATH=$(pwd)/lxd/_dist
        cd lxd
        make deps
        make deps | grep '^export ' > $HOME/build-env
        
    - name: Make
      run: |
        export GOPATH=$(pwd)/lxd/_dist
        export GOBIN=$GOPATH/bin
        source $HOME/build-env
        cd lxd
        make
        
    - name: Customize
      run: |
        grep LD_LIBRARY_PATH $HOME/build-env | sed -e "s@$(pwd)/lxd/_dist@\${GOPATH}@g" -e 's/$/:${LD_LIBRARY_PATH}/'
        
    - name: Archive
      run: tar -czf ${{ github.event.inputs.release_name }}_${{ matrix.os }}.tar.gz lxd/

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.inputs.release_name }}_${{ matrix.os }}
        path: ${{ github.event.inputs.release_name }}_${{ matrix.os }}.tar.gz  
